### ISSUE TITLE
ojo resolve does not create patch

### ISSUE THREAD

**Issue by nivkner** [jneem/ojo#2]
after creating conflicting lines and resolving them with `ojo resolve` I get `Created patch PbM-iY1pe6qZT69j4Fh8B-fdse2p1r9mefT2z0apSRcQ=`

however, using the command `ojo patch apply PbM-iY1pe6qZT69j4Fh8B-fdse2p1r9mefT2z0apSRcQ=` returns `Error: There is no patch with hash "PbM-iY1pe6qZT69j4Fh8B-fdse2p1r9mefT2z0apSRcQ="`

using `diff` on `.ojo/db` before and after the resolution shows that no changes where made to the file.

the db of the repo is:

```
---
current_branch: master
storage:
  next_inode: 1
  contents:
    ? patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
      node: 0
    : - 108
      - 105
      - 110
      - 101
      - 49
      - 10
    ? patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
      node: 0
    : - 108
      - 105
      - 110
      - 101
      - 48
      - 10
    ? patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
      node: 2
    : - 108
      - 105
      - 110
      - 101
      - 50
      - 97
      - 108
      - 116
      - 10
    ? patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
      node: 1
    : - 108
      - 105
      - 110
      - 101
      - 50
      - 10
  branches:
    master:
      n: 0
  graggles:
    ? n: 0
    : nodes:
        - patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
          node: 0
        - patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
          node: 0
        - patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
          node: 2
        - patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
          node: 1
      deleted_nodes: []
      edges:
        - - patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
            node: 0
          - kind: Live
            dest:
              patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
              node: 2
            patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
        - - patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
            node: 0
          - kind: Live
            dest:
              patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
              node: 1
            patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
        - - patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
            node: 0
          - kind: Live
            dest:
              patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
              node: 0
            patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
      back_edges:
        - - patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
            node: 0
          - kind: Live
            dest:
              patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
              node: 0
            patch: SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
        - - patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
            node: 2
          - kind: Live
            dest:
              patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
              node: 0
            patch: sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
        - - patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
            node: 1
          - kind: Live
            dest:
              patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
              node: 0
            patch: wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
      deleted_partition:
        ranks: {}
        parent_map: {}
        child_map: []
      pseudo_edge_reasons: []
      reason_pseudo_edges: []
      dirty_reps: []
  patches:
    sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=: "---\nchanges:\n  - NewNode:\n      id:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 2\n      contents:\n        - 108\n        - 105\n        - 110\n        - 101\n        - 50\n        - 97\n        - 108\n        - 116\n        - 10\n  - NewEdge:\n      src:\n        patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=\n        node: 0\n      dest:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 2\nheader:\n  author: name\n  description: patch4\n  timestamp: \"2019-02-22T22:04:44.939048092Z\"\ndeps:\n  - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ="
    wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=: "---\nchanges:\n  - NewNode:\n      id:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 1\n      contents:\n        - 108\n        - 105\n        - 110\n        - 101\n        - 50\n        - 10\n  - NewEdge:\n      src:\n        patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=\n        node: 0\n      dest:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 1\nheader:\n  author: name\n  description: patch2\n  timestamp: \"2019-02-22T22:03:27.353704847Z\"\ndeps:\n  - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ="
    QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=: "---\nchanges:\n  - NewNode:\n      id:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 0\n      contents:\n        - 108\n        - 105\n        - 110\n        - 101\n        - 49\n        - 10\nheader:\n  author: name\n  description: patch1\n  timestamp: \"2019-02-22T22:03:07.180757707Z\"\ndeps: []"
    SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=: "---\nchanges:\n  - NewNode:\n      id:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 0\n      contents:\n        - 108\n        - 105\n        - 110\n        - 101\n        - 48\n        - 10\n  - NewEdge:\n      src:\n        patch: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n        node: 0\n      dest:\n        patch: QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=\n        node: 0\nheader:\n  author: name\n  description: patch3\n  timestamp: \"2019-02-22T22:04:01.801882510Z\"\ndeps:\n  - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ="
  branch_patches:
    - - master
      - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
    - - master
      - SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
    - - master
      - sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
    - - master
      - wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
  patch_deps:
    - - SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
      - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
    - - sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
      - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
    - - wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
      - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
  patch_rev_deps:
    - - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
      - SPinzATzjMdhPbIOiEuv1g3APvD_XMSTb-P1fC1in0E=
    - - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
      - sy2zb8-ZQCOd4g2NlJWzFGgJXkCpLPF16-OTewoe8zw=
    - - QD7cHiAVTYWI3C_jgAUYZl5b7UShhJPson-wmDtIzjQ=
      - wUGPSV1ovfKBv61n6NXzYU6AZB5RyACfpE-wlaliEAE=
```
